apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: farmconnect
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      serviceAccountName: farmconnect-sa
      containers:
        - name: config-server
          image: "thiwanka365/farmconnect-config-server:5d2b8bde90e9d774c5a5e0575f10cb898704a5a9"
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: farmconnect-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
